server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mySql?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    data-username: root
    data-password:
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wangzifeng.mysqlboot.login.model.*  # 注意：对应实体类的路径
